USE mace_tracking;

CREATE TABLE IF NOT EXISTS inventory (
  id INT PRIMARY KEY AUTO_INCREMENT,
  van_id INT NOT NULL,
  bu VARCHAR(50) NOT NULL,
  item VARCHAR(100) NOT NULL,
  qty INT NOT NULL DEFAULT 0,
  uom VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (van_id) REFERENCES vans(id) ON DELETE CASCADE
);